CREATE TABLE IF NOT EXISTS quote_revisions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quote_id INT NOT NULL,
  version_no INT NOT NULL,
  reason VARCHAR(255) NULL,
  status_snapshot VARCHAR(30) NULL,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  shipping_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  overhead_charge DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  other_expenses DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  installation_expenses DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  valid_until DATE NULL,
  lead_time VARCHAR(150) NULL,
  warranty VARCHAR(150) NULL,
  payment_terms TEXT NULL,
  admin_notes TEXT NULL,
  meta_json JSON NULL,
  created_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_quote_revision_version (quote_id, version_no),
  KEY idx_quote_revisions_quote_created (quote_id, created_at),
  CONSTRAINT fk_quote_revisions_quote FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE CASCADE,
  CONSTRAINT fk_quote_revisions_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS quote_revision_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  revision_id INT NOT NULL,
  quote_item_id INT NULL,
  product_id INT NULL,
  product_name VARCHAR(255) NOT NULL,
  sku VARCHAR(120) NULL,
  brand VARCHAR(150) NULL,
  qty INT NOT NULL DEFAULT 1,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  line_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_quote_revision_items_revision (revision_id),
  KEY idx_quote_revision_items_product (product_id),
  CONSTRAINT fk_quote_revision_items_revision FOREIGN KEY (revision_id) REFERENCES quote_revisions(id) ON DELETE CASCADE,
  CONSTRAINT fk_quote_revision_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
